= sqlitear(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: SQLite Archive Manual
:man source: sqlitear

== NAME

sqlitear - example of how to insert/replace or select a blob in sqlite

== SYNOPSIS

*sqlitear* [OPTIONS] -c|-x|-t -f DATABASE [FILE...]

== DESCRIPTION

*sqlitear(1)* saves many files together into a single database, and can
restore individual files from the database.

== OPTIONS

**-f or --file**::
	Set the path to database.

**-c or --create**::
	Create a new database.

**-x or --extract**::
	Extract file from a database.

**-t or --list**::
	List the contents of a database.

**-h or --help**::
	Display this message.

**-V or --version**::
	Display the version.

== EXIT STATUS

Exits success if everything succeed; exits failure otherwise.

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright (C) 2018 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
